{
 "title": "TPU Dash",
 "tags": [
  "tpu",
  "gke",
  "libtpu"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Node-pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node-Pool Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(status) ({__name__=\"kubernetes.io/node_pool/status\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node-Pool Interruption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(interruption_type, interruption_reason) ({__name__=\"kubernetes.io/node_pool/interruption_count\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node-Pool Status Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(node_pool_name) ({__name__=\"kubernetes.io/node_pool/multi_host/available\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TPU Chip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "TPU Duty Cycle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(pod_name) ({__name__=\"kubernetes.io/container/accelerator/duty_cycle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPU Tensorcore Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(accelerator_id) ({__name__=\"kubernetes.io/container/accelerator/tensorcore_utilization\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPU HBM Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod_name) ({__name__=\"kubernetes.io/container/accelerator/memory_bandwidth_utilization\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPU Memory Used/Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod_name) ({__name__=\"kubernetes.io/container/accelerator/memory_total\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod_name) ({__name__=\"kubernetes.io/container/accelerator/memory_used\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "LibTPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "LibTPU - TensorCore Util",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(instance, chip) (libtpu_tensorcore_utilization_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LibTPU - Duty Cycle Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(instance, chip) (libtpu_duty_cycle_pct)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LibTPU - HBM Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance, chip) (libtpu_hbm_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LibTPU - HLO Execution Timing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by(instance, core_type_id, stat) (libtpu_hlo_execution_timing{stat=~\"mean|p90|p999\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LibTPU - HLO Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min by(instance, core_type_id) (libtpu_hlo_queue_size)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LibTPU - HBM Capacity Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance, chip) (libtpu_hbm_capacity_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}